### ISSUE TITLE
hi ~  I like this but can u tell me how to not hide the status bar in the main controller?

### ISSUE THREAD

**Issue by aa2246740** [dekatotoro/SlideMenuControllerSwift#1]
when the left bar show up ,the main view's status bar become invisible , how to make it appear??
thank you ! ur code is great

**Comment by sameera26** [comment]
Hi, I need to show status bar in right and left view controllers. Please give me a suggestion to implement this. 

Thanks!

**Comment by kostapappas** [comment]
just do    SlideMenuOptions.hideStatusBar = false before push your slideMenuController
