### ISSUE TITLE
SlideMenuOption let to var

### ISSUE THREAD

**Issue by gali8** [dekatotoro/SlideMenuControllerSwift#12]
Hi dekatotoro, thanks for your work!

I'm using your SlideMenuController (customized to use UIStoryboardSegue to connect any UIViewController with left or right menus, so I can prevent to write code) and I want to update the options values from the self.options class.

These values are defined like let so they are not assignable. 

I suggest to you to replace these "let" to "var", so we can edit the options values before the "self.initView()" function, when our class inherits from the SlideMenuController.

Enjoy!

**Comment by dekatotoro** [comment]
Thank you for pointing this out.

I was going to try to change. 
Please wait a little longer.

**Comment by dekatotoro** [comment]
Changed at this commit.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/6a8855599adabe4f1375dcb447365376dcb48253
