### ISSUE TITLE
Left gesture not working after selecting item from menu

### ISSUE THREAD

**Issue by asafl1976** [dekatotoro/SlideMenuControllerSwift#122]
If you initialise SlideMenuController with just mainViewController and leftMenuViewController (using init function at line 70 in SlideMenuController.swift), once you tap an item from the menu, i.e. tap the Swift row in your example, the swipe from left gesture stops working. What actually kills the swipe from left gesture is a line in function closeRightWithVelocity (which I think should be called since I have only left menu)
THANKS

**Comment by dhiaeldeen** [comment]
did you solve this? i have the same problem...

if you think the solution is here, what line to comment or delete from these?

    public func closeRightWithVelocity(velocity: CGFloat) {
    
        let xOrigin: CGFloat = rightContainerView.frame.origin.x
        let finalXOrigin: CGFloat = CGRectGetWidth(view.bounds)
    
        var frame: CGRect = rightContainerView.frame
        frame.origin.x = finalXOrigin
    
        var duration: NSTimeInterval = Double(SlideMenuOptions.animationDuration)
        if velocity != 0.0 {
            duration = Double(fabs(xOrigin - CGRectGetWidth(view.bounds)) / velocity)
            duration = Double(fmax(0.1, fmin(1.0, duration)))
        }
    
        UIView.animateWithDuration(duration, delay: 0.0, options: UIViewAnimationOptions.CurveEaseInOut, animations: { [weak self]() -> Void in
            if let strongSelf = self {
                strongSelf.rightContainerView.frame = frame
                strongSelf.opacityView.layer.opacity = 0.0
                strongSelf.mainContainerView.transform = CGAffineTransformMakeScale(1.0, 1.0)
            }
            }) { [weak self](Bool) -> Void in
                if let strongSelf = self {
                    strongSelf.removeShadow(strongSelf.rightContainerView)
                    strongSelf.enableContentInteraction()
                    strongSelf.rightViewController?.endAppearanceTransition()
                }
        }
    }

**Comment by dhiaeldeen** [comment]
add the rest of the UIViewControllers to ExSlideMenuController, that solved it for me.

**Comment by asafl1976** [comment]
Find the function public func changeMainViewController(mainViewController: UIViewController,  close: Bool) and replace it with this one:

public func changeMainViewController(mainViewController: UIViewController,  close: Bool) {
        
        removeViewController(self.mainViewController)
        self.mainViewController = mainViewController
        setUpViewController(mainContainerView, targetViewController: mainViewController)
        if (close) {
            if leftViewController != nil
            {
                closeLeft()
            }
            if rightViewController != nil
            {
                closeRight()
            }
        }
    }

**Comment by asafl1976** [comment]
public func changeMainViewController(mainViewController: UIViewController,  close: Bool) {
        removeViewController(self.mainViewController)
        self.mainViewController = mainViewController
        setUpViewController(mainContainerView, targetViewController: mainViewController)
        if (close) {
            if leftViewController != nil
            {
                closeLeft()
            }
            if rightViewController != nil
            {
                closeRight()
            }
        }
    }
