### ISSUE TITLE
Does it have an obj-c version? Or I can create an one?

### ISSUE THREAD

**Issue by allenlinli** [dekatotoro/SlideMenuControllerSwift#123]
I want to use this lib in my project, but I don't know how to mix Swift with Obj-c (is it stable?).
So I want to write an Obj-c version of this library if there's no one.

May I do that or is there a similar library?

Cheers,

Allen

**Comment by Pluto-Y** [comment]
Yes, I have wrote a SlideMenuControllerOC, But I don't publish it.

**Comment by Pluto-Y** [comment]
You can use this lib in OC Project.

**Comment by Pluto-Y** [comment]
You can do like this one:

Step by step swift integration for Xcode Objc-based project:

- Create new *.swift file (in Xcode) or add it by using Finder
- Add swift bridging empty header if Xcode have not done this before (see 4 below)

- Implement your Swift class by using @objc attribute:

-
import UIKit

@objc class Hello : NSObject {
    func sayHello () {
        println("Hi there!")
    }
}



- Open Build Settings and check this parameters:
    - Product Module Name : myproject
    - Defines Module : YES
    - Embedded Content Contains Swift : YES
    - Install Objective-C Compatibility Header : YES
    - Objective-C Bridging Header : $(SRCROOT)/Sources/SwiftBridging.h

- Import header (which is auto generated by Xcode) in your *.m file

#import "myproject-Swift.h"



- Clean and rebuild your Xcode project
- Profit!

**Comment by allenlinli** [comment]
Thank you, I didn't work it out yet. But I will try it.
Cheers,
