### ISSUE TITLE
Integrate top searchbar as rightview controller?

### ISSUE THREAD

**Issue by kerimsari** [dekatotoro/SlideMenuControllerSwift#124]
Hello,

Do you know how can i integrate searchbar as rightviewcontroller?

Please suggest
Thanks
Kerim

**Comment by Pluto-Y** [comment]
Have you succeded?

**Comment by kerimsari** [comment]
Yes :)
Actually i didn't integrate it as a right view controller.
I've "added" searchbar to the slidemenucontroller.

**Comment by Pluto-Y** [comment]
Great!
