### ISSUE TITLE
Can I use one seperate slide menus for each viewcontrollers?

### ISSUE THREAD

**Issue by pointphoton** [dekatotoro/SlideMenuControllerSwift#125]
Hi. I'm new ios and swift.

Thanks this framefork and your kindlyi generous efforts.

I need to use seperatly slide menus for each viewcontroller. I need different maincontrollers without using appdelegate.

If i use app delegate fucntion. Last function's controller become maincontroller.

At least Can you tell me is it possible to not lost more much time.

**Comment by Pluto-Y** [comment]
Maybe you can call the method `changeMainViewController:close:`, `changeLeftViewController:closeLeft:` and `changeRightViewController:closeRight:` in the defferent last function's controller.

**Comment by pointphoton** [comment]
Thank you.

**Comment by Pluto-Y** [comment]
You are welcome.
