### ISSUE TITLE
Left-menu is opening  behind controller. (solved)

### ISSUE THREAD

**Issue by pointphoton** [dekatotoro/SlideMenuControllerSwift#126]
01 . [<a href="http://tinypic.com?ref=2hqyyh4" target="_blank"><img src="http://i64.tinypic.com/2hqyyh4.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

02 . [<a href="http://tinypic.com?ref=10hkqwh" target="_blank"><img src="http://i63.tinypic.com/10hkqwh.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

03 . [<a href="http://tinypic.com?ref=eqwlyq" target="_blank"><img src="http://i63.tinypic.com/eqwlyq.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

Hi Good days.. 

* I don't use appdelegate.

* I have to use many uiviewcontrollers.

* At the upper photos maincontoller and leftcontroller are used. And third one is "Controller 1" labelled uiviewcontroller which has open-menu button. And Fourth one is other controller which is shown in image 3.

* MainController is exactly like this :
[<a href="http://tinypic.com?ref=15ow74x" target="_blank"><img src="http://i68.tinypic.com/15ow74x.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

* LeftMenuController is similar your sample.

* And "Controller 1" is like this : 
[<a href="http://tinypic.com?ref=1y6b2c" target="_blank"><img src="http://i67.tinypic.com/1y6b2c.jpg" border="0" alt="Image and video hosting by TinyPic"></a>](url)

*** Thank you in advance. Can you suggest me anything?

**Comment by Pluto-Y** [comment]
I can't review the picture.

**Comment by pointphoton** [comment]
Sorry, It is fixed.

**Comment by pointphoton** [comment]
`   override func awakeFromNib() {
        if let controller = self.storyboard?.instantiateViewControllerWithIdentifier("Controller1ViewController") {
            self.mainViewController = controller
        }
        if let controller = self.storyboard?.instantiateViewControllerWithIdentifier("LeftViewController") {
            self.leftViewController = controller
        }
        super.awakeFromNib()
    }`

Xcode is giving below exception, if  I call this fuction in Controller1. 

> 
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
> 

Thanks in advance. Have a nice day.

**Comment by pointphoton** [comment]
My problem is solved.

1-  awakeFromNib() is removed.

2- Controller1  doesn't extends SlideMenuController anymore.

3- And I call these codes before controller1 is not opened.

` let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("Controller1ViewController") as! Controller1
        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("LeftViewController") as! LeftViewController
        let nvc: UINavigationController = UINavigationController(rootViewController: mainViewController)
       leftViewController.mainViewController = nvc
       let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController)
        // navigate to next view
        self.presentViewController(slideMenuController, animated: false, completion: nil)`
