### ISSUE TITLE
Push with UINavigationController

### ISSUE THREAD

**Issue by mrbamboovn** [dekatotoro/SlideMenuControllerSwift#13]
Hello,

I am using this library and I have trouble with PUSH ViewController.

Could you please help me to suggest how to use this lib with UINavigationController ?

Thanks

**Comment by dekatotoro** [comment]
Hi. Thank you feedback.

you can use together. 
But  If you enable the left menu when Viewcontroller you push, It is not recommended because the standard pop gesture suffers.

**Comment by htarwara6245** [comment]
Are u embedding navigation controller to left menu controller?No,u can't.I tried once.You can also try by navigating to other view using this code in left view controller,Like,Java,C++ Menu

**Comment by dekatotoro** [comment]
There, it is embedded the navigationcontroller to the left of the view? You had better transition to embed navigationcontroller to main.

**Comment by htarwara6245** [comment]
yeah it was true.Thanks dekatotoro
