### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Kevin-Tran-** [dekatotoro/SlideMenuControllerSwift#132]
Hi. I'm having some issues getting it to build after a pod install. I am getting the following: http://i.imgur.com/hfjUbDm.png

Let me know if you need additional information

Pod install file:
 use_frameworks!

target 'MyApp' do

  pod 'SlideMenuControllerSwift', '~> 2.1'

end

**Comment by Pluto-Y** [comment]
Have you update the Xcode 7.3? It's the new future of the Swift 3.0 and it is supported by Xcode 7.3.
