### ISSUE TITLE
Right ViewController with UIImage shows up on MainVC. 

### ISSUE THREAD

**Issue by ashuVerizon** [dekatotoro/SlideMenuControllerSwift#133]
First of all, thanks a lot for the awesome slider menu library! I just started using it and its great however I came upon a but and then I tested your sample app to see if I can recreate it.

Basically if you have a UIImage on Right Side VC then that image is displayed on the Main VC and it also gets stretched beyond the VC when you open the right VC. I have attached the screen shot.

It changes the Main VC's frame. 

Red is the background color or an UIImage which is full screen image view. 

![simulator screen shot mar 30 2016 11 12 41 pm](https://cloud.githubusercontent.com/assets/13735843/14167418/02a7f232-f6d0-11e5-85b2-cdd6669ceba1.png)

![simulator screen shot mar 30 2016 11 11 55 pm](https://cloud.githubusercontent.com/assets/13735843/14167422/06ee32fc-f6d0-11e5-9310-f931da2010eb.png)

**Comment by zirinisp** [comment]
I had the same problem and the solution is very simple.

        imageView.clipsToBounds = true

This way the image will be crop inside its frame and will not go outside it.

**Comment by Pluto-Y** [comment]
Thanks @zirinisp.

**Comment by ashuVerizon** [comment]
@zirinisp @Pluto-Y  Sorry but that's not working. The only way I can make it work is if I close the right view at the very beginning while setting up the Main and Right VC.
