### ISSUE TITLE
make Slider Tableview Expandable

### ISSUE THREAD

**Issue by Bhavesh-Limbachiya** [dekatotoro/SlideMenuControllerSwift#136]
if i click one of menu than it will expand with another options ,
how can i do it with this slider ?

**Comment by Pluto-Y** [comment]
@Bhavesh-Limbachiya What's the meaning? Can you explain further particulars？

**Comment by bagwanshoaib** [comment]
@Pluto-Y  #submenu

How to create submenu in slidemenucontrollerswift?

**Comment by Pluto-Y** [comment]
Just think left(or right) menu as a normal UIViewController.
