### ISSUE TITLE
simultaneousGestureRecognizers should have a setting for the menu gesture to take priority over other gestures

### ISSUE THREAD

**Issue by AustinDu** [dekatotoro/SlideMenuControllerSwift#139]
I'm currently using the slide menu on top a view controller (which is set as the "Main" view) containing a page view controller (as a container). When setting simultaneousGestureRecognizers to false, the page view swiping gestures take priority over the gesture to open the menu, when I desire for it to be the other way around. Is this the intended function of this option when set to false, or is it bugged? Thanks!

**Comment by Dashyn** [comment]
Hi, 
I had the same problem yesterday and i found a function to prioritize gesture on the slide menu :
`public func addPriorityToMenuGesuture(targetScrollView: UIScrollView)`

**Comment by itleo31** [comment]
I got the same issue. My subview has a LongPress gesture. And its callback be called parallel with menu gesture. How can I make it only happen 1.

**Comment by Codeido** [comment]
As told by @Dashyn use 
`public func addPriorityToMenuGesuture(targetScrollView: UIScrollView)`
In this way you can specify if you want menu gesuture give priority to than targetScrollView.
