### ISSUE TITLE
viewWillDisAppearが呼ばれないことについて

### ISSUE THREAD

**Issue by sisuc** [dekatotoro/SlideMenuControllerSwift#14]
こんにちは。
ライブラリーどうもありがとうございます。
（日本語で申し訳ありません。）

さっそく質問ですが、
Gesturesでスライドメニューを表示させると、
viewDidAppearとviewWillDisAppearが呼ばれます。

メニューアイテムをタップしてスライドメニューを表示させると、
viewDidAppearだけ呼ばれて、そのごタップしても何も呼ばれません。

そのご、Gesturesでスライドメニューを表示させると、viewWillDisAppearだけ呼ばれます。

ごれは仕様でしょうか。

**Comment by dekatotoro** [comment]
Hi, 

I'm sorry in English.

I did there not care, Its behavior It is strange.
I will confirm.

**Comment by dekatotoro** [comment]
Hi

Supported this commit.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/d0127f3715cfbb5555ec18fb29764a2a15416cce

Please check.

**Comment by sisuc** [comment]
Thank you for your support.

And i have a one question.
I want use modalTransitionStyle or modalPresentationStyle when tapped menu
and display ViewController.
How can i this..?
Please help me.

Best Regards.

2015-03-20 18:51 GMT+09:00 Yuji Hato <notifications@github.com>:
