### ISSUE TITLE
Can I use your frame without making the viewcontroller as window.rootViewcontroller?

### ISSUE THREAD

**Issue by YzStyle** [dekatotoro/SlideMenuControllerSwift#142]
as the title,I already have a rootViewController,dont want to do something in AppDelegate.swift,Could you give me some demo or advice?
tips:I find some other Issues about my problem,but It isn't useful...I'm a swift newer

**Comment by Pluto-Y** [comment]
@YzStyle Of course, you can.
You can push or present the SlideMenuController when you need.
Just think the SlideMenuController like as a general UIViewController.

**Comment by YzStyle** [comment]
oh！！！Thx，I'm misguided by demo.

**Comment by Pluto-Y** [comment]
You are welcome.
