### ISSUE TITLE
LeftPanGesture will not work after rotate. Use init(mainViewController: UIViewController, leftMenuViewController: UIViewController)

### ISSUE THREAD

**Issue by Leoshu** [dekatotoro/SlideMenuControllerSwift#144]
If SlideMenuController.init(mainViewController: UIViewController, leftMenuViewController: UIViewController), after device rotate ,the method that isRightOpen() always be true. So, handleLeftPanGesture(panGesture: UIPanGestureRecognizer) will not work correctly.

My workaround:
1. SlideMenuOptions.rightPanFromBezel = false
2. Use SlideMenuController.init(mainViewController: UIViewController, leftMenuViewController: UIViewController, rightMenuViewController: UIViewController). The rightMenuViewController just set UIViewController().

**Comment by Pluto-Y** [comment]
@Leoshu What version do you use now?

**Comment by Leoshu** [comment]
pod 'SlideMenuControllerSwift', :git => 'https://github.com/dekatotoro/SlideMenuControllerSwift.git', :branch => 'swift2.1'

**Comment by Pluto-Y** [comment]
Maybe you can update to the master version?
Can you update the swift version?

**Comment by Leoshu** [comment]
I develop in swift 2.1. Should I still use master branch?

**Comment by Pluto-Y** [comment]
No, the master has support to the newest swift version.

**Comment by Leoshu** [comment]
OK. thanks. Let me try it.

**Comment by Leoshu** [comment]
It works pretty good at version SlideMenuControllerSwift 2.1.1.
Thanks a lot.

**Comment by Pluto-Y** [comment]
Have you fixed the bug?
