### ISSUE TITLE
I download demo project and have a lot of errors.

### ISSUE THREAD

**Issue by PetyaxD** [dekatotoro/SlideMenuControllerSwift#145]
Hello, can u help me why its done. I download your test project and can't build it cause 18 errors SlideMenuControllerSwift.swift file. Its only not work for me or anything else is the problem?

**Comment by Pluto-Y** [comment]
What version Xcode do you use now?

**Comment by PetyaxD** [comment]
Version 7.1

**Comment by Pluto-Y** [comment]
The master branch needs Xcode 7.3.
It had been updated for the new swift feature.
Maybe you can update the Xcode.

**Comment by PetyaxD** [comment]
sure, I've started it. thanks for the help and for your work!

**Comment by Pluto-Y** [comment]
You are welcome.

**Comment by PetyaxD** [comment]
i installed the latest version (7.2.1) and this is the same. Have u any idea? :)

**Comment by PetyaxD** [comment]
sry 7,3 the latest, now i installed it but the problem is still have :/

**Comment by Pluto-Y** [comment]
Can you post the error message?

**Comment by PetyaxD** [comment]
now i restart my pc after Xcode update and i doesn't have the errors now, i start the project it shows build is successful but the simulator didn't start :/ any idea?

**Comment by Pluto-Y** [comment]
I have no idea, can you post some picture?

**Comment by PetyaxD** [comment]
there is no error message, its build successfully but the simulator didn't start. i tested a blank project, my Xcode is ok.
<img width="1920" alt="kepernyofoto 2016-04-13 - 22 58 34" src="https://cloud.githubusercontent.com/assets/7137583/14509189/60b97430-01cb-11e6-84c4-5f1e3bbf75ee.png">

**Comment by Pluto-Y** [comment]
@PetyaxD Maybe you should change the Scheme.
![image](https://cloud.githubusercontent.com/assets/10654142/14516340/76b4cf64-0234-11e6-8eb4-7950bf2afb4c.png)

**Comment by PetyaxD** [comment]
nice, it works. thanks a lot
