### ISSUE TITLE
Missing argument, coder:

### ISSUE THREAD

**Issue by PetyaxD** [dekatotoro/SlideMenuControllerSwift#147]
now any other problems solved, but have a new one :D 
i install with cocoa pods, import in app delegate copy the test code but get this error: Missing argument, coder:
<img width="1172" alt="kepernyofoto 2016-04-14 - 12 02 06" src="https://cloud.githubusercontent.com/assets/7137583/14524496/ef228dac-0238-11e6-81d4-6f7d035e1c52.png">

**Comment by PetyaxD** [comment]
i was the ugly, sry. I found the problem its my fault, I start learn Swift in a couple of weeks ago. I close this section, its solved thx

**Comment by brdjx** [comment]
What was your problem? Have the same problem myself.

**Comment by PetyaxD** [comment]
sry i don't remember, maybe i download an other version from it. i can check it for u at the end of the next week, now I'm not home to check it :/

**Comment by brdjx** [comment]
Okay, thanks a lot. I'd appreciate it a lot if you did send the solution when you get a chance.

Cheers

**Comment by emremct** [comment]
I also have the same problem :/
