### ISSUE TITLE
Ambiguous 

### ISSUE THREAD

**Issue by J-phantom** [dekatotoro/SlideMenuControllerSwift#149]
hi  
when i inherit sildermenucontroller.swift 
error :`Ambiguous use of 'toggleLeft()'`

**Comment by Pluto-Y** [comment]
Have you used keyword `override`?

**Comment by J-phantom** [comment]
I solved my problem. Thank you 
i can you see problem  [#150](https://github.com/dekatotoro/SlideMenuControllerSwift/issues/150)

**Comment by omidkh68** [comment]
@J-Arji how can you fix your Ambiguous problem?
