### ISSUE TITLE
Trying to change view controller from a dashboard button but the menu didn't appear

### ISSUE THREAD

**Issue by PetyaxD** [dekatotoro/SlideMenuControllerSwift#155]
Trying to change view controller from a dashboard button but the menu didn't appear, but the gestures is working. u have any idea?
code:

    func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        // handle tap events
        print("You selected cell #\(indexPath.item)!")
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let programViewController = storyboard.instantiateViewControllerWithIdentifier("ProgramViewController") as! ProgramViewController
        
        self.slideMenuController()?.changeMainViewController(programViewController, close: true)
    }

**Comment by PetyaxD** [comment]
its solved

**Comment by Pluto-Y** [comment]
@PetyaxD Thanks for issues.

**Comment by Tindi** [comment]
@PetyaxD how did you solve it? Getting the same issue.

**Comment by PetyaxD** [comment]
sry I'm on holiday, if i get home, i send u the answer :)

**Comment by aakarshsasi** [comment]
> sry I'm on holiday, if i get home, i send u the answer :)

Send it please
