### ISSUE TITLE
Drawer under status bar

### ISSUE THREAD

**Issue by mggeray** [dekatotoro/SlideMenuControllerSwift#165]
Is it possible to display the drawer under the status bar?

**Comment by Pluto-Y** [comment]
What's your meaning? 
Show the status bar, right?

**Comment by mggeray** [comment]
@Pluto-Y, ah yes. That's what I meant.
When displaying the drawer, the status bar is also displayed.

**Comment by Pluto-Y** [comment]
Please try this, `SlideMenuOptions.hideStatusBar = false`.

**Comment by Pluto-Y** [comment]
@mggeray  Is it ok?

**Comment by mggeray** [comment]
@Pluto-Y, sorry for the late reply. Yes this is OK.
Thank you!

**Comment by karthisiva** [comment]
How can i show navigation controller bar?
