### ISSUE TITLE
Slide mainViewController with menu viewcontroller

### ISSUE THREAD

**Issue by kaunteya** [dekatotoro/SlideMenuControllerSwift#174]
As seen in the screenshot below, How can I make mainViewcontroller slide along with left/right menu view controller?

![Imgur](http://i.imgur.com/lrBLKY0.png)

**Comment by Codeido** [comment]
Hi @kaunteya 
If you use the last version of the Library
`pod 'SlideMenuControllerSwift', :git => 'https://github.com/dekatotoro/SlideMenuControllerSwift'`

you can use the new property "contentViewDrag".

**Comment by Codeido** [comment]
Now last version on cocoapods is the 2.2.0. Please, use this release.

Thanks
