### ISSUE TITLE
Only have left menu

### ISSUE THREAD

**Issue by fishfisher** [dekatotoro/SlideMenuControllerSwift#175]
I do not want to have any right menu, but I am not able to pass nil in rightMenuViewController.

Is there a way to only have a left menu?

**Comment by fishfisher** [comment]
Sorry for my bad research. The option is there:)

**Comment by PuneetKohli** [comment]
It'd be great if you could share since it's not obvious - I've been trying for a while

**Comment by fishfisher** [comment]
Yeah, sure. You can specify this when you initialize the SlideMenuController:

let slideMenuWithOnlyLeft = SlideMenuController(mainViewController: **, leftMenuViewController: **)

let slideMenuWithLeftAndRight = SlideMenuController(mainViewController: **, leftMenuViewController: **, rightMenuViewController: **)

**Comment by PuneetKohli** [comment]
Yeah, it seemed intuitive to me that there would've been a constructor like that, so I tried it out a bit after commenting here.

Thanks anyways though! :)

Dev should upgrade the documentation though it doesn't cover a lot of stuff
