### ISSUE TITLE
Push subContentsview from left menu

### ISSUE THREAD

**Issue by leizard** [dekatotoro/SlideMenuControllerSwift#179]
Hi, your side menu is awesome, I love it. Just one little thing, how can i push a subContentView to the current navigation controller of the main view when I click to a item on left menu ? Is it possible to get the current main view of left menu and make a push. I tried add these code in didSelectRowAtIndexPath method of LeftMenuController: 

`
let storyboard = UIStoryboard(name: "SubContentsViewController", bundle: nil)
let subContentsVC = storyboard.instantiateViewControllerWithIdentifier("SubContentsViewController") as! SubContentsViewController
  self.slideMenuController()?.mainViewController!.navigationController?.pushViewController(subContentsVC, animated: true)
`
but it didn't work ?
Could you please give me some ideas about implementing this ? 
Thank you.

**Comment by leizard** [comment]
nvm, I just did it:

`
            let storyboard = UIStoryboard(name: "SubContentsViewController", bundle: nil)
            let subContentsVC = storyboard.instantiateViewControllerWithIdentifier("SubContentsViewController") as! SubContentsViewController
            let nvc = self.slideMenuController()?.mainViewController as! UINavigationController
            nvc.pushViewController(subContentsVC, animated: true)
            // close
            self.slideMenuController()?.closeLeft()
`

Thank you for great package now I'm adding it to my project 👍

**Comment by pankajIos** [comment]
How We go to other view controller on click on menu list item under "didSelectRowAtIndexPath" method.

**Comment by pankajIos** [comment]
Having Write Code below:
anyone may help me ?        
Thanks in Advanced


let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let subContentsVC = storyboard.instantiateViewControllerWithIdentifier("AboutusVC") as! AboutusVC
            
        let nvc = self.slideMenuController()?.mainViewController as! UINavigationController
            nvc.pushViewController(subContentsVC, animated: true)
        self.slideMenuController()?.closeLeft()

**Comment by HappyIosDeveloper** [comment]
I found this useful too:
I got back to my MainViewController then run this block with delegation:

        guard let myVC = self.storyboard?.instantiateViewController(withIdentifier: "MyViewController") else { return }
        let navController = UINavigationController(rootViewController: myVC)
        self.slideMenuController()?.present(navController, animated: true, completion: nil)

```
