### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by ivangodfather** [dekatotoro/SlideMenuControllerSwift#18]
Im trying to use it with swift 1.2 and the code need some changes, will be updated? And also when be available through cocoapods?

**Comment by dekatotoro** [comment]
Yes, I'm going corresponding Swift1.2 and Cocoapods.
Please wait a little longer.

Thank you feedback !

**Comment by zikoops** [comment]
Hello dekatotoro, 
i'm just updated xcode 6.3 & swift 1.2, so i have a problem in func slideLeftForGestureRecognizer
" |= is unavailable: use the || operator instead "
i have edited follow by warning but when i slide to the left of screen, it still does not working, same for slide to the right.
Please fix it,
Thank you!

**Comment by evenh** [comment]
Thank you for such a great component @dekatotoro. Do you have an ETA for Swift 1.2 & Cocoapods support?

**Comment by SemperIdem** [comment]
@zikoops 
We can't use "|=" or "||=" anymore, it's very strange that Apple doesn't change the explaination of Operators in Swift Programming Guide. Maybe it's a bug of swift1.2.
You can modify the statement to 
slide = slide || self.options.panFromBezel && self.isLeftPointContainedWithinBezelRect(point)
and
slide = slide || self.options.rightPanFromBezel && self.isRightPointContainedWithinBezelRect(point)
in corresponding methods.
It works for me^_^

**Comment by aks0020** [comment]
I have made pull request for this see this it works with Swift 1.2:
https://github.com/dekatotoro/SlideMenuControllerSwift/pull/21

**Comment by zikoops** [comment]
@SemperIdem 
Thank you, it works for me.

**Comment by dekatotoro** [comment]
Sorry Swift1.2 correspondence is late.
Swfit1.2 Was supported.
