### ISSUE TITLE
; expected after pod install

### ISSUE THREAD

**Issue by milindjoshi297** [dekatotoro/SlideMenuControllerSwift#180]
![screen shot 2016-06-15 at 9 48 08 pm](https://cloud.githubusercontent.com/assets/18531021/16088049/f56c8542-3342-11e6-8a97-e9fe1d1a74d6.png)
After pod 'SlideMenuControllerSwift', i was able to see pod installed successfully. but whenever i tried to build the project it says '; expected' with 18 errors. These are showing in Pods, not in my workspace. Please help me to resolve this.

**Comment by Codeido** [comment]
Can you try to install first the version 2.2.0 and if it doesn't work, the v2.1.1?

Thanks

**Comment by milindjoshi297** [comment]
Thanks @Codeido ... I am using swift 2.1.1, so i used pod 'SlideMenuControllerSwift', '2.1' and it worked !! Thanks a lot.
