### ISSUE TITLE
Migration to Swift 3

### ISSUE THREAD

**Issue by Codeido** [dekatotoro/SlideMenuControllerSwift#181]
I think that we can consider a migration to Swift 3 as soon as possible, creating a new branch for this.

In this way, with the GM of Xcode 8 in autumn we are ready for this transition.

**Comment by indrajitsinh** [comment]
Does any update on this ?

**Comment by hyb175** [comment]
Put up a PR for it https://github.com/dekatotoro/SlideMenuControllerSwift/pull/199
Feedback welcome!

**Comment by t-jonas** [comment]
Hi, i tried your branch but i get the following errors:

![bildschirmfoto 2016-08-17 um 14 16 45](https://cloud.githubusercontent.com/assets/16743134/17735925/505f23a6-6485-11e6-903d-d0926071b157.png)

**Comment by cms5x** [comment]
This may partly answer the issue: http://stackoverflow.com/questions/38732948/the-supportedinterfaceorientations-method-doesnt-override-any-method-from-its-s

**Comment by nadav96** [comment]
@t-jonas I managed to Fix the complier errors, [here is the PR] (https://github.com/hyb175/SlideMenuControllerSwift/pull/1) to @hyb175  fork

**Comment by Codeido** [comment]
Hi!
The actual version works great with Swift 2.3 and Swift 3.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/a74a0a26c21a49dcd4ed0c24fb352a68f89eff33

Thanks
- Paolo
