### ISSUE TITLE
SlideMenuControllerDelegate not work

### ISSUE THREAD

**Issue by leizard** [dekatotoro/SlideMenuControllerSwift#184]
Hi, first of all thank you so much for the awesome package.
I have a UITableViewController named . In the viewDidLoad method, I set navigation bar right item:
```
    override func viewDidLoad() {
        // Set navigation bar right item for right slide menu
        self.setNavigationBarRightItem()
    }
```
Then I can use right slide menu properly.
Then I want to use SlideMenuControllerDelegate to catch slide menu open/close events so I add:
```
extension MyUITableViewController : SlideMenuControllerDelegate {
  
    func leftWillOpen() {
        print("SlideMenuControllerDelegate: leftWillOpen")
    }
    
    func leftDidOpen() {
        print("SlideMenuControllerDelegate: leftDidOpen")
    }
    
    func leftWillClose() {
        print("SlideMenuControllerDelegate: leftWillClose")
    }
    
    func leftDidClose() {
        print("SlideMenuControllerDelegate: leftDidClose")
    }
    
    func rightWillOpen() {
        print("SlideMenuControllerDelegate: rightWillOpen")
    }
    
    func rightDidOpen() {
        print("SlideMenuControllerDelegate: rightDidOpen")
    }
    
    func rightWillClose() {
        print("SlideMenuControllerDelegate: rightWillClose")
    }
    
    func rightDidClose() {
        print("SlideMenuControllerDelegate: rightDidClose")
    }
}
```
But it doesn't work.
Did I miss something, please tell me. Thank you very much.

**Comment by timlehr** [comment]
To catch the events you have to specify a delegation first. You can do so by adding 
`slideMenuController()?.delegate = self`to the view controller, which implements the delegate (event) functions. For example, add the line in your `override func viewDidLoad()` of the UIViewController. Hope that helps.

**Comment by leizard** [comment]
Hi. I get it working now by extending the SlideMenuControllerDelegate and catch the global event. This is bad practice I think but working. I will try your suggestion. 
Thank you very much.

**Comment by kumareshsaran** [comment]
I put all the code for slideMenucontroller but the button did not show the left side menu while touching the button. i don't know what is the issues in my code
