### ISSUE TITLE
SlideMenuControllerDelegate doesn't work

### ISSUE THREAD

**Issue by yojkim** [dekatotoro/SlideMenuControllerSwift#188]
```
class ContainerVC: SlideMenuController, SlideMenuControllerDelegate {
    
    override func awakeFromNib() {
        if let mainVC = self.storyboard?.instantiateViewControllerWithIdentifier("OfficialRootVC") {
            self.mainViewController = mainVC
        }
        
        if let rightVC = self.storyboard?.instantiateViewControllerWithIdentifier("OfficialRightVC") {
            self.rightViewController = rightVC
        }
        
        super.awakeFromNib()
    }

    func rightDidClose() {
        print("right")
    }
    
    func rightWillClose() {
        print("right")
    }

    /*...Some Code...*/
}
```

I implement my code like this, OfficialRootVC is UINavigationController and OfficialRightVC is custom UITableViewController.
Slide Menu works but print("right") isn't called when menu is closed.

**Comment by littlemozart** [comment]
@yojkim I meet the same problem. How did you solve it?

**Comment by yojkim** [comment]
@littlemozart I'm not sure but I moved the delegate `SlideMenuControllerDelegate` to its own ViewController called "OfficialVC" then implement `rightDidClose()` delegate method.
Lastly, Add `self.slideMenuController?.delegate = self;` in `viewDidLoad()`

I think it may be changed because too much time have passed :)

**Comment by littlemozart** [comment]
@yojkim Yes, I use the same way to deal with it. Thank you all the same.
