### ISSUE TITLE
ViewControllers

### ISSUE THREAD

**Issue by kinott** [dekatotoro/SlideMenuControllerSwift#2]
Hi! I'm really stuck with customizing.
I added button in LeftViewController, linked it to a new TableViewController, added code and have no side menu in total )))
I guess i missing something.
Could you make a very light example of this menu, which toggle between different views?
Somethink like this:
![Image of example]
(https://raw.githubusercontent.com/romaonthego/RESideMenu/master/Demo.gif?2)
This helps me a lot to discover Swift. 
Thank you very much!

**Comment by htarwara6245** [comment]
I really love your navigation controller.
But,i found some bugs on rotate.i am newbie to swift.So,i don't know much about UIgesture,or many UI feature in swift.
So,if you don't mind,try testing this app on ipad mini,iphone 6plus,ipad air by rotating.You will see right view controller appear on the screen that can't be draw or release.
Please help me with this coz i want to use your lib.Thank you sir.

Waiting for your reply...

**Comment by dekatotoro** [comment]
Hi, Thank you for your comment.
I'm going to the correspondence of rotation future.
Please wait for a while.

**Comment by dekatotoro** [comment]
Hi, I was rotated rotated correspondence in this commit. Please confirm.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/4adcedf5d3ebda72108f90c186cbf6e98e9ec536

**Comment by htarwara6245** [comment]
I see now.You disable the slide when it rotates.Thanks for your feedback.Really loves it.Now i will apply to my project.But,one thing is i use only left slide out in my project and i am facing these problems.

>When i add table cell and to create menu like youtube and add segue to other view controller by embedding navigation controller in left view controller,the error 
"Terminating app due to uncaught exception 'NSGenericException', reason: 'Could not find a navigation controller for segue 'showMenuDetail'. Push segues can only be used when the source controller is managed by an instance of UINavigationController." happen.

If you don't mind,can you check that problem concern with your left view controller?
If you upload example that fix my problem,i will really love to use it.
Thank you sir.Really love your navigation fix.

**Comment by dekatotoro** [comment]
Hi,Thank you feedback.
It might be difficult to connect with segue from leftviewcontroller.
Please stop the embed navigationController to the left menu and
 set the navigationController to mainViewController.
When it is tap the left tableview menu, please tell that it was pressed to mainviewcontroller, using notification or delegate.
It is also possible t to operate by acquiring directly mainViewController instance from the left of the tableview menu.
```
if let nav = self.slideMenuController()?.mainViewController as? UINavigationController {
    let yourMainViewController = nav.childViewControllers[0] as? YourMainViewController
    //some code
}
```

Regards,
htarwara6245

**Comment by htarwara6245** [comment]
You mean,i have to use main view controller to display the detail of left menu.
Why can't i replace other view controller to main view controller when i tapped one of the menu from left in table cell?
Please sir,I am newbie to swift.Thanks for your reply.really appreciate it

**Comment by dekatotoro** [comment]
I have changed the example of sample project.
I do not know what you want, but please try to check.

**Comment by htarwara6245** [comment]
Yeah...that is exactly what i want...Thank you..Really Thank you so much for giving me some time to my problem.
Thank you sir.

**Comment by dekatotoro** [comment]
Hi, It was good what you want.
The example of a sample project was a little poor, it was just right as an opportunity to fix.
Thank you in the future.
