### ISSUE TITLE
self.slideMenuController()?.removeLeftGestures() when use Lansdcape

### ISSUE THREAD

**Issue by sisuc** [dekatotoro/SlideMenuControllerSwift#20]
thank you for your support.
i use 'self.slideMenuController()?.removeLeftGestures()'. 
but that code was ignored on Landscape interface.
please check this issue.
thank you.

**Comment by dekatotoro** [comment]
Hi, Thank you feedback.
Since the far better how to respond is not found,Please correspond with each of viewController feel like links below.

https://github.com/dekatotoro/SlideMenuControllerSwift/blob/master/SlideMenuControllerSwift/NonMenuController.swift#L26

**Comment by dekatotoro** [comment]
Because like no problem, I will close.
