### ISSUE TITLE
Change leftMenuViewController at runtime

### ISSUE THREAD

**Issue by efrenps** [dekatotoro/SlideMenuControllerSwift#202]
Hi! Thanks for your awesome work. I have a little question, I want to allow two differents leftMenuViewController, one for guest user and the other for logged users.  I need to use two differents ViewController for this,  because menu layout are differents.

How I can change the ViewController for menu at runtime ?

Thank you in advance.

**Comment by efrenps** [comment]
`` 
 if let slideMenuController = self.slideMenuController() {
                    let storyboard = UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
                    if(Meteor.client.loggedIn()){
                        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("LeftMenuController") as! LeftMenuController
                        leftViewController.mainViewController = slideMenuController.mainViewController
                        
                        //let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
                        //appDelegate.slideMenuController!.leftViewController = leftViewController;
                        self.appDelegate.slideMenuController = ExSlideMenuController(mainViewController:slideMenuController.mainViewController!, leftMenuViewController: leftViewController)
                    }
                }

``

**Comment by timlehr** [comment]
You should be able to change your leftMenuViewController by calling `changeLeftViewController(leftViewController: UIViewController, closeLeft: Bool)` on your container view.
