### ISSUE TITLE
Add Swift 3 Compatibility

### ISSUE THREAD

**Issue by rbugajewski** [dekatotoro/SlideMenuControllerSwift#207]
With the upcoming release of Swift 3 (and the newly introduced incompatibility to Swift 2.2 and older in Xcode 8) it would be great to have a separate branch with Swift 3 compatibility.

Please consider also adding a Swift 2.3 branch for people who can’t migrate to Swift 3, because of other dependencies.

**Comment by Codeido** [comment]
Hi @rbugajewski.

The actual version works great with Swift 2.3 and Swift 3.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/a74a0a26c21a49dcd4ed0c24fb352a68f89eff33
