### ISSUE TITLE
how can i use swift2.3 and swift3.0 pod in Xcode8

### ISSUE THREAD

**Issue by wangbourne** [dekatotoro/SlideMenuControllerSwift#212]
can i use this way?

pod 'SlideMenuControllerSwift',:git => 'https://github.com/dekatotoro/SlideMenuControllerSwift.git',:branch => 'swift3'

pod 'SlideMenuControllerSwift',:git => 'https://github.com/dekatotoro/SlideMenuControllerSwift.git',:branch => 'swift2.3'

**Comment by tthbalazs** [comment]
The swift 3 version is on the `master` branch, so:

### For swift3:
```ruby
pod 'SlideMenuControllerSwift', git: 'https://github.com/dekatotoro/SlideMenuControllerSwift.git', branch: 'master'
```

### For swift2.x you can currently use the cocoapods version
```ruby
pod 'SlideMenuControllerSwift'
```
or

```ruby
pod 'SlideMenuControllerSwift', git: 'https://github.com/dekatotoro/SlideMenuControllerSwift.git', branch: 'swift2.3'
```
