### ISSUE TITLE
Doesnt work in Xcode 8 / Swift 3 / Cocoapods 1.1

### ISSUE THREAD

**Issue by protspace** [dekatotoro/SlideMenuControllerSwift#215]
`/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:11:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:12:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:13:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:14:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:15:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:16:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:17:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:18:5: 'optional' requirements are an Objective-C compatibility feature; add '@objc'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:84:80: 'NSBundle' has been renamed to 'Bundle'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:84:21: Initializer does not override a designated initializer from its superclass
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:161:26: Method does not override any method from its superclass
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:190:26: Method does not override any method from its superclass
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:197:26: Method does not override any method from its superclass
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:29:46: 'CGSizeMake' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:38:76: Cannot call value of non-function type 'UIColor'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:334:48: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:335:47: 'CGPointZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:338:60: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:414:48: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:415:47: 'CGPointZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:418:60: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:89:9: 'init' is a member of the type; use 'type(of: ...)' to initialize a new object of the same dynamic type
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:96:9: 'init' is a member of the type; use 'type(of: ...)' to initialize a new object of the same dynamic type
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:103:9: 'init' is a member of the type; use 'type(of: ...)' to initialize a new object of the same dynamic type
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:118:63: Cannot call value of non-function type 'UIColor'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:119:48: 'FlexibleHeight' has been renamed to 'flexibleHeight'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:119:65: 'FlexibleWidth' has been renamed to 'flexibleWidth'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:120:14: 'insertSubview(_:atIndex:)' has been renamed to 'insertSubview(_:at:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:128:60: 'FlexibleHeight' has been renamed to 'flexibleHeight'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:128:95: 'FlexibleWidth' has been renamed to 'flexibleWidth'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:130:14: 'insertSubview(_:atIndex:)' has been renamed to 'insertSubview(_:at:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:140:63: Cannot call value of non-function type 'UIColor'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:141:65: 'FlexibleHeight' has been renamed to 'flexibleHeight'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:142:14: 'insertSubview(_:atIndex:)' has been renamed to 'insertSubview(_:at:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:154:64: Cannot call value of non-function type 'UIColor'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:155:66: 'FlexibleHeight' has been renamed to 'flexibleHeight'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:156:14: 'insertSubview(_:atIndex:)' has been renamed to 'insertSubview(_:at:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:162:9: Value of type 'UIViewController' has no member 'viewWillTransitionToSize'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:163:39: 'CGAffineTransformMakeScale' has been replaced by 'CGAffineTransform.init(scaleX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:164:27: 'hidden' has been renamed to 'isHidden'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:165:28: 'hidden' has been renamed to 'isHidden'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:170:36: 'hidden' has been renamed to 'isHidden'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:171:37: 'hidden' has been renamed to 'isHidden'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:167:21: 'animateAlongsideTransition(_:completion:)' has been renamed to 'animate(alongsideTransition:completion:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:187:45: 'None' has been renamed to 'none'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:192:65: Cannot call value of non-function type 'UIInterfaceOrientationMask'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:194:43: 'All' has been renamed to 'all'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:198:52: Cannot call value of non-function type 'Bool'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:203:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:204:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:205:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:218:30: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:220:15: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:232:31: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:234:15: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:245:31: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:257:32: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:266:89: Value of type 'SlideMenuController' has no member 'handleLeftPanGesture'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:283:90: Value of type 'SlideMenuController' has no member 'handleRightPanGesture'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:352:43: 'Began' has been renamed to 'began'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:353:47: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:353:84: 'Cancelled' has been renamed to 'cancelled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:353:125: 'Failed' has been renamed to 'failed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:364:59: 'locationInView' has been renamed to 'location(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:369:33: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:371:43: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:372:47: 'Began' has been renamed to 'began'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:372:83: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:376:55: 'translationInView' has been renamed to 'translation(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:377:63: Missing argument label 'translation:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:380:43: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:380:75: 'Cancelled' has been renamed to 'cancelled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:381:47: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:386:51: 'velocityInView' has been renamed to 'velocity(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:387:69: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:393:42: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:395:27: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:400:43: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:403:27: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:406:43: 'Failed' has been renamed to 'failed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:406:76: 'Possible' has been renamed to 'possible'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:432:39: 'Began' has been renamed to 'began'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:433:44: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:433:82: 'Cancelled' has been renamed to 'cancelled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:433:124: 'Failed' has been renamed to 'failed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:444:56: 'locationInView' has been renamed to 'location(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:450:29: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:452:39: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:453:44: 'Began' has been renamed to 'began'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:453:81: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:457:51: 'translationInView' has been renamed to 'translation(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:458:61: Missing argument label 'translation:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:462:39: 'Ended' has been renamed to 'ended'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:462:71: 'Cancelled' has been renamed to 'cancelled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:463:44: 'Changed' has been renamed to 'changed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:468:48: 'velocityInView' has been renamed to 'velocity(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:469:66: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:475:39: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:477:23: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:482:40: Missing argument label 'velocity:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:485:23: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:487:39: 'Failed' has been renamed to 'failed'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:487:72: 'Possible' has been renamed to 'possible'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:501:23: 'NSTimeInterval' has been renamed to 'TimeInterval'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:507:25: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:530:37: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:535:23: 'NSTimeInterval' has been renamed to 'TimeInterval'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:541:25: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:567:23: 'NSTimeInterval' has been renamed to 'TimeInterval'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:593:37: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:598:23: 'NSTimeInterval' has been renamed to 'TimeInterval'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:627:19: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:647:19: Missing argument label 'trackAction:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:654:83: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:658:53: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:663:30: Missing argument label 'viewController:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:665:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:698:30: Missing argument label 'viewController:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:700:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:707:30: Missing argument label 'viewController:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:709:28: Missing argument label 'targetView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:720:16: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:748:54: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:815:36: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:837:83: 'CGAffineTransformMakeTranslation' has been replaced by 'CGAffineTransform.init(translationX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:837:159: 'CGAffineTransformMakeScale' has been replaced by 'CGAffineTransform.init(scaleX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:845:83: 'CGAffineTransformMakeTranslation' has been replaced by 'CGAffineTransform.init(translationX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:845:159: 'CGAffineTransformMakeScale' has been replaced by 'CGAffineTransform.init(scaleX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:853:95: 'CGPath' has been renamed to 'cgPath'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:871:27: 'userInteractionEnabled' has been renamed to 'isUserInteractionEnabled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:875:27: 'userInteractionEnabled' has been renamed to 'isUserInteractionEnabled'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:881:64: Cannot call value of non-function type 'UIApplication'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:880:13: 'dispatch_async' has been replaced by instance method 'DispatchQueue.asynchronously(execute:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:880:28: 'dispatch_get_main_queue()' has been replaced by property 'DispatchQueue.main'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:891:64: Cannot call value of non-function type 'UIApplication'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:890:13: 'dispatch_async' has been replaced by instance method 'DispatchQueue.asynchronously(execute:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:890:28: 'dispatch_get_main_queue()' has been replaced by property 'DispatchQueue.main'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:903:28: 'didMoveToParentViewController' has been renamed to 'didMove(toParentViewController:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:911:29: 'willMoveToParentViewController' has been renamed to 'willMove(toParentViewController:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:924:39: 'CGAffineTransformMakeScale' has been replaced by 'CGAffineTransform.init(scaleX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:925:22: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:931:37: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:936:39: 'CGAffineTransformMakeScale' has been replaced by 'CGAffineTransform.init(scaleX:y:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:937:22: Missing argument label 'targetContainerView:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:944:36: 'locationInView' has been renamed to 'location(in:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:947:49: Missing argument label 'gesture:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:949:54: Missing argument label 'gesture:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:951:68: Missing argument label 'point:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:953:70: Missing argument label 'point:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:965:101: Missing argument label 'point:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:970:41: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:971:36: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:973:13: 'CGRectDivide' is unavailable: Use divided(atDistance:from:)
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:973:89: 'MinXEdge' has been renamed to 'minXEdge'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:974:20: 'CGRectContainsPoint' has been replaced by instance method 'CGRect.contains(_:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:981:16: 'CGRectContainsPoint' has been replaced by instance method 'CGRect.contains(_:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:987:108: Missing argument label 'point:' in call
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:992:42: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:993:36: 'CGRectZero' is unavailable in Swift
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:994:39: 'CGRectGetWidth' has been replaced by property 'CGRect.width'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:996:13: 'CGRectDivide' is unavailable: Use divided(atDistance:from:)
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:996:90: 'MinXEdge' has been renamed to 'minXEdge'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:998:20: 'CGRectContainsPoint' has been replaced by instance method 'CGRect.contains(_:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:1005:16: 'CGRectContainsPoint' has been replaced by instance method 'CGRect.contains(_:)'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:1019:46: 'parentViewController' has been renamed to 'parent'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:1025:107: 'Plain' has been renamed to 'plain'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:1030:108: 'Plain' has been renamed to 'plain'
/Users/eugensagidulin/repos/ProjectName/Pods/SlideMenuControllerSwift/Source/SlideMenuController.swift:1063:51: 'requireGestureRecognizerToFail' has been renamed to 'require(toFail:)'`

http://prntscr.com/ciqmj7

**Comment by protspace** [comment]
Ok, should use master branch explicitly pod 'SlideMenuControllerSwift', :git => 'https://github.com/dekatotoro/SlideMenuControllerSwift.git', :branch => 'master'

**Comment by karthisiva** [comment]
i have added pod file like you said, but then its asking me to convert to 3.0 pop up..any samples
