### ISSUE TITLE
Not working after Xcode 6 Beta 3

### ISSUE THREAD

**Issue by TDMarko** [dekatotoro/SlideMenuControllerSwift#22]
- init must have a convenience
- 'as' must be 'as!'
- gesture recognizer does not work on mainView (couldn't fix that yet)

**Comment by lsisuc** [comment]
+1

i use the Swift 1.2 on Xcode 6 Beta 3

**Comment by sisuc** [comment]
+1

I use the Swift 1.2 on Xcode 6 Beta 3

**Comment by lorenzOliveto** [comment]
I resolved the problem with the gesture recognizers replacing those lines:
        slide |= self.options.panFromBezel && self.isLeftPointContainedWithinBezelRect(point)
        slide |= self.options.rightPanFromBezel && self.isRightPointContainedWithinBezelRect(point)
 with the following:
        slide = slide || self.options.panFromBezel && self.isLeftPointContainedWithinBezelRect(point)
        slide = slide || self.options.rightPanFromBezel && self.isRightPointContainedWithinBezelRect(point)

I replaced also the init method with this:
    internal init() {
        super.init(nibName: nil, bundle: nil)
    }

**Comment by krumjahn** [comment]
+ 1

**Comment by TimmersThomas** [comment]
Made a small fork/pull-request for Swift 1.2 support: #23 :)

**Comment by dekatotoro** [comment]
Sorry Swift1.2 correspondence is late.
Swfit1.2 Was supported.

If you are developing in the swift1.1, please use branch of swift1.1
