### ISSUE TITLE
black view if SlideMenuOptions.contentViewOpacity = 1

### ISSUE THREAD

**Issue by wangbourne** [dekatotoro/SlideMenuControllerSwift#232]
When i set SlideMenuOptions.contentViewOpacity = 1 and swipe in left view, the right part becomes black.

i thought the parameter contentViewOpacity is used to adjust left view's transparency, which should not affect right view. does my understanding make sense?

![image](https://cloud.githubusercontent.com/assets/2090084/19261948/9f8fa338-8fd7-11e6-9bab-f0ac07823df9.png)

**Comment by Pluto-Y** [comment]
Yes, but you can see the sources:
```
        // initView method
        view.insertSubview(mainContainerView, at: 0)
//        ... something else
        view.insertSubview(opacityView, at: 1)
//        ... something else
            view.insertSubview(leftContainerView, at: 2)
//        ... something else
            view.insertSubview(rightContainerView, at: 3)
```

The black view is the `opacityView` and the view's `backgroundColor` default is black.
