### ISSUE TITLE
The starting screen goes black

### ISSUE THREAD

**Issue by codinggenie** [dekatotoro/SlideMenuControllerSwift#251]
This code is written in AppDelegate

```
// initialized the controller
let slideMenuController = SlideMenuController(mainViewController: controller, leftMenuViewController: controller, rightMenuViewController: controller)
self.window?.rootViewController = slideMenuController
```

I just want the same viewController to be displayed in all the 3 slides.
But when I start the app, the screen is just black. 
Is this is a bug ?

**Comment by Pluto-Y** [comment]
No, the `SlideMenuController` is a container view controller, and the main, left and right controllers' view will be added to SlideMenuController's view, so you cannot add same view multiple times.
