### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by pkc456** [dekatotoro/SlideMenuControllerSwift#253]
Xcode 8, OS 10.11.6

I integrate sidemenu controller using cocoapods. Sometime the build error occur. What is the possible reason for this. Below is issue navigator logs. I have to clean-build and reinstall the application to work again.

dyld_sim`dyld_fatal_error:
    0x40000 <+0>: int3   
->  0x40001 <+1>: nop    

dyld: Library not loaded: @rpath/SlideMenuControllerSwift.framework/SlideMenuControllerSwift
  Referenced from: /Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/IndigoTest
  Reason: no suitable image found.  Did find:
	/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift: required code signature missing for '/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift'

	/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift: required code signature missing for '/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift'

	/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift: required code signature missing for '/Users/Pardeep/Library/Developer/CoreSimulator/Devices/49C4CF61-1716-49AD-B439-F5A92162B77E/data/Containers/Bundle/Application/1F6892BB-EA6D-4BE7-8F9F-98AC61FD9A94/IndigoTest.app/Frameworks/SlideMenuControllerSwift.framework/SlideMenuControllerSwift'

**Comment by aesmail** [comment]
I'm having the same issue. I already spent a few hours trying to fix this problem but nothing worked so far.

I found [http://stackoverflow.com/questions/40110392/required-code-signature-missing-for-a-library](this).

**Comment by patiljignesh** [comment]
Tried those, none seemed to work for me. So I just re-installed the lib.

**Comment by aesmail** [comment]
@patiljignesh that's what they say in the second or third answer I believe.
but yeah, reinstalling the pod fixed the problem.
