### ISSUE TITLE
Cannot convert value of type

### ISSUE THREAD

**Issue by felstell** [dekatotoro/SlideMenuControllerSwift#256]
Hello
I was try use your Pod (thanks for this), but when i put block of code in AppDelegate - i have an error.
(http://prntscr.com/dd4wwg - this is a screenshot)
My MainViewController type - UIViewController. What's wrong with him?
Please, help me.

**Comment by felstell** [comment]
Can anyone help me?

**Comment by JustinDMoore** [comment]
I'm having the same error. Any updates?

**Comment by Pluto-Y** [comment]
@felstell What's your swift version? 2.3 or 3.0? And what's your SlideMenuController version?

**Comment by felstell** [comment]
@Pluto-Y Swift 3. 
But i find solve for this problem: 
I did this Container View
<img width="539" alt="screenshot at 01 14-30-05" src="https://cloud.githubusercontent.com/assets/8091787/20792495/20f76618-b7d3-11e6-9e4a-4fca47886ddf.png">
And i this LeftViewController
<img width="413" alt="screenshot at 01 14-30-15" src="https://cloud.githubusercontent.com/assets/8091787/20792524/4a84acb6-b7d3-11e6-833d-d5a0c6b7d965.png">
Then i'm add only  "import SlideMenuControllerSwift" in my AppDelegate 
<img width="1079" alt="screenshot at 01 14-35-25" src="https://cloud.githubusercontent.com/assets/8091787/20792545/6b9c346e-b7d3-11e6-8a10-4ac4533f838f.png">
In storyboard i have one Container View, and two Navigation Controller with Storyboard ID:
<img width="1053" alt="screenshot at 01 14-31-40" src="https://cloud.githubusercontent.com/assets/8091787/20792572/9758381e-b7d3-11e6-8796-dbee417e333f.png">
<img width="1056" alt="screenshot at 01 14-32-19" src="https://cloud.githubusercontent.com/assets/8091787/20792576/9c17949e-b7d3-11e6-8627-2b0ff9eb448d.png">

And it's work! :)

I hope this help anyone with his trouble
