### ISSUE TITLE
How can you avoid specifying a right Viewcontroller?

### ISSUE THREAD

**Issue by Traubenfuchs** [dekatotoro/SlideMenuControllerSwift#26]
If you only want to have one menu.

**Comment by ppeelen** [comment]
Leave out the `, rightMenuViewController: rightViewController`. E.g. `let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController, rightMenuViewController: rightViewController)`

**Comment by dekatotoro** [comment]
Thank you instead of reply !
