### ISSUE TITLE
not able to plug in simple swift project

### ISSUE THREAD

**Issue by Imtayaz** [dekatotoro/SlideMenuControllerSwift#27]
![screen shot 2015-05-06 at 12 06 36 am](https://cloud.githubusercontent.com/assets/5706597/7474363/31b1ec9a-f384-11e4-9bad-28253b8eee6c.png)
Hi,
I like your controls, this is really helpful,
Some reason I am not able to plug in my project. 

I have navigation view project, in home view I need to include only left slide view. 

Thanks in advance,
Imtayaz

**Comment by Imtayaz** [comment]
![screen shot 2015-05-06 at 12 06 36 am](https://cloud.githubusercontent.com/assets/5706597/7474356/259929dc-f384-11e4-968f-3280330bf51a.png)

**Comment by dekatotoro** [comment]
hi,
Do you want to use only the leftViewController ?
If so, try to do as follows.

ex)
let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController)

**Comment by Imtayaz** [comment]
Hi Yuji, 
Thanks for quick reply, some reason I am not able to use this controls, I will retry tonight and let you know if I have same issue. 

Thanks,
Imtee

**Comment by dekatotoro** [comment]
All right.

**Comment by dekatotoro** [comment]
Because like no problem, I will close.
