### ISSUE TITLE
Previous/Back Navigation Not Working

### ISSUE THREAD

**Issue by dhruv270** [dekatotoro/SlideMenuControllerSwift#275]
Thank you for very good library of SlideMenu.

I have one issue of previous button. Please suggest/guide someone how to manage back navigation issue using this pod?
I have the same issue as `_ = navigationController?.popViewController(animated: true)` is not working for me.

**Comment by sreejithsn** [comment]
same issue

**Comment by dhruv270** [comment]
I have resolved this issue by using:
`self.navigationController?.pushViewController(personListViewController, animated: true)`
