### ISSUE TITLE
ContentScale of mainViewController

### ISSUE THREAD

**Issue by iHamzaaK** [dekatotoro/SlideMenuControllerSwift#293]
@dekatotoro can you please tell me how to make the mainViewController scale fit to the whole screen .. As you can see in the below picture the mainvc contentSize is transformed

Thanks in advance

<img width="460" alt="screen shot 2017-03-06 at 11 35 27 am" src="https://cloud.githubusercontent.com/assets/10392416/23599157/09b07908-0261-11e7-8fb9-20df2c4c4c37.png">

**Comment by kizitonwose** [comment]
You need to change the `contentViewScale` in `SlideMenuOptions`.  Setting the value to "1" will fix your issue. 

`SlideMenuOptions.contentViewScale = 1` 

Although according to issue #263, using the value "1" breaks navigation. If that's the case for you, then use "0.999999"
