### ISSUE TITLE
Usage with existing storyboard based layout?

### ISSUE THREAD

**Issue by m-t-space** [dekatotoro/SlideMenuControllerSwift#3]
Hi, great work, I'm new to swift and wondering if you could provide a little insight as to how to set this up without instantiating the viewControllers from the storyboard, and integrating it with an already in process app?

**Comment by dekatotoro** [comment]
Hi, Thank you for your comment. 
The pattern set this up without instantiating the viewControllers from the storyboard If what?  Is xib?
I felt that if you provide the sample code might be resolved.

**Comment by m-t-space** [comment]
Thanks for the reply, I didn't however have the identifier set in the storyboard, among other issues, I've figured it out, thanks!
