### ISSUE TITLE
Bug found when change the orientation of device 

### ISSUE THREAD

**Issue by littlemozart** [dekatotoro/SlideMenuControllerSwift#312]
hi, I open the slide menu in horizontal then rotate the screen. When I open the slide menu again, I found that there maybe something wrong at the top of the menu. By the way, rotating the screen will force the menu to close without calling the function will close nor did close? How can I do to monitor it?
![img_0862](https://cloud.githubusercontent.com/assets/18299148/25205706/914fb7f4-2596-11e7-88d1-c738b8c73063.PNG)

**Comment by victorlsn** [comment]
I have that same problem when I send the application to background with the drawer open and then resume it.

**Comment by littlemozart** [comment]
@victorlsn I try to solve this problem by add the codes under.
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        slideMenuController()?.closeLeft()
    }

**Comment by victorlsn** [comment]
Thanks!
