### ISSUE TITLE
Access LeftMenuProtocol from a view

### ISSUE THREAD

**Issue by albertkim** [dekatotoro/SlideMenuControllerSwift#32]
I'm having trouble allowing the first shown page to segue to another view automatically (if not logged in, go to login view, etc)

The problem from the example is that the LeftViewController passes in the LeftMenuProtocol as 'delegate' to the created views.

However, that is only done when the user opens a view from the left menu, not from AppDelegate. If a view is loaded in from AppDelegate, there seems to be no way (that i know of) to access LeftMenuProtocol. 

Some help would be appreciated.

**Comment by albertkim** [comment]
I have resolved this by loading the initial view in the viewDidLoad() method of the LeftViewController. Doing so automatically initializes the 'delegate' variable of the views, and it allows me to use the changeViewController() method from inside the views.

**Comment by moschino1** [comment]
I albertkim,
I'm new in IOS and have the same problem.
My main page is a login UI and then programmatically I call a UI where I want to link the LeftViewController with the menu.
Could you please post the code you added to the LeftViewController to do it working?
My approach was to add the code in the AppDelegate directly to the page is calling the LeftViewController in the viewDidLoad() method, but is not working.
Thanks a lot for your help
