### ISSUE TITLE
add shadow to main view 

### ISSUE THREAD

**Issue by ahmedsafadii** [dekatotoro/SlideMenuControllerSwift#325]
its possible to add shadow to main view like this

![image](https://user-images.githubusercontent.com/6974081/27320190-b946b69a-559d-11e7-9b25-790613e33258.jpg)

**Comment by waseem-shah-ios** [comment]
Please user 

SlideMenuOptions.shadowOpacity = 0.5

before init slideMenu like this

SlideMenuOptions.shadowOpacity = 0.5
let slideMenuController = SlideMenuController(mainViewController: mainViewController!, leftMenuViewController: menuView!)

**Comment by ahmedsafadii** [comment]
thanks @waseem-shah-ios :D
