### ISSUE TITLE
I want to know which main view controller that i am currently see behind the menu

### ISSUE THREAD

**Issue by htarwara6245** [dekatotoro/SlideMenuControllerSwift#33]
When i tapped Swift menu,it show me Swift View Controller.When i slide out to view the menu again
http://puu.sh/hW37U/4717187aa2.png
how to know the current view in my foreground?
http://puu.sh/hW38R/10b1d40bd5.png

Thank You 
With Regards.

**Comment by htarwara6245** [comment]
Any Help?Please?

**Comment by dekatotoro** [comment]
Hi,

An easy way is not available now.
Please to override the SlideMenuController#track method for tracking.
the following Enum is have defined.
```
    enum TrackAction {
        case TapOpen
        case TapClose
        case FlickOpen
        case FlickClose
    }
```

Please try to acquiring and processing are displaying viewController as follows:
```
self.slideMenuController()?.mainViewController
```

If so demand is high, consider a good interface.
