### ISSUE TITLE
How to use if MainViewController is not first controller in app?

### ISSUE THREAD

**Issue by anhhtbk** [dekatotoro/SlideMenuControllerSwift#333]
I want to add SlideMenu to MainView after LoginView. SlideMenu don't show in LoginView, only show from MainView.
How to do that? 
Thanks!

**Comment by kalyan711987kalyan** [comment]
How did you handle it?
I'm also looking for same.

**Comment by anhhtbk** [comment]
Did you try `changeMainViewController`?
- First, `login` is `mainVC`, disable slide menu
- Second, `changeMainViewController` as you like, enable slide menu
