### ISSUE TITLE
viewWillAppear is not calling for mainViewController

### ISSUE THREAD

**Issue by RomanPodymov** [dekatotoro/SlideMenuControllerSwift#338]
Dear guys.
Thank you for your library. I like to use it in my projects.
However after update to version 3.0.2 I see that viewWillAppear is not calling for my mainViewController that I use for SlideMenuController instance. mainViewController is a subclass of UINavigationController. Could you please tell me why it happened? I see that now in version 3.0.2 the following code was commented inside viewWillAppear:
`self.mainViewController?.viewWillAppear(animated)`
Probably it is the reason. But I cannot understand why this line of code was commented.
Thank you in advance.

**Comment by wdcurry** [comment]
Have you tried uncommenting that line and running your project(s)? If no crashes occur, then you are good to go. It is very bad coding practice to NOT call the super in any override unless there are strong mitigating circumstances.

**Comment by RomanPodymov** [comment]
Hello @wdcurry .
I want to show you full code of this method:
```
override open func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    //automatically called 
    //self.mainViewController?.viewWillAppear(animated)
}
```
As you can see super call is not missing. But one line is commented now and it leads to error. I cannot understand why it was commented in version 3.0.2. Probably this version was not tested for UINavigationController as a mainViewController.

**Comment by wdcurry** [comment]
ahh, i see now. Without looking at the code directly, this is a poor design within the repo. There should never be any extraneous called into overridable views as such. This looks like a late-night effort to stop something from crashing. That your coding is working dependent on that odd setup suggests you as well might want to pull back and re-examine your object calls.

I have found the biggest time-waster in my current project is SlideMenu. The hooks, the structure, the requirements to make it all just work, are beyond the merit of it, but my time budget is too tight to remove it. It is *almost* great, but needs a re-think. I don't mean to insult the coders on the project, as know how these things go. I have spent many hours pushing to make a design work knowing full well i should start over, but instead just keep coding workarounds, so i get it.

**Comment by AmauryDef** [comment]
Did you find out what was wrong ?

I'm having the same issue and I haven't been able to figure out how to solving while I've been working on more than a day

**Comment by RomanPodymov** [comment]
Hello @AmauryDef 
Today I tried to use code from branch 'swift4' and I still have this error (that viewWillAppear is not calling). No ideas for now.

**Comment by AmauryDef** [comment]
Thank you for replying me @RomanPodymov .

If I find an answer, I'll tell you.

**Comment by AmauryDef** [comment]
Hi Roman,

I finally found a way to reload the view. I'm launching the viewDidLoad but I guess you can do the same with the viewWillAppear.

You can put this code in the viewDidLoad of your MainActivity:

        NotificationCenter.default.addObserver(self, selector: #selector(HomeViewController.viewDidLoad), name: NSNotification.Name(rawValue: "FilterKey"), object: nil)

And you can change HomeViewController.viewDidLoad by : theNameOfYourMainView.viewWillAppear

Then, in my case, after pressing a button I have those two lines of code that make the refresh of the page and close the Slide-Menu, you can put it wherever you want in the controller of your side menu:

        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "FilterKey"), object: nil)
        closeRight()

Hope I helped you, if I did not, don't hesitate to contact me, I'm not expert in Swift but I'll do my best to help you

**Comment by RomanPodymov** [comment]
Hello @AmauryDef ,
Thank you for your solution. But how did you found that we must use "FilterKey"?

**Comment by AmauryDef** [comment]
Actually the term "FilterKey" is just the name that I gave to this Observer. You can put the name that you want, but you will have to use the same word in the two places where I wrote "FilterKey".

I used that name cause I'm using a side menu to filter the elements of the TableView in my MainController.

Did I help you with my solution ?

**Comment by RomanPodymov** [comment]
Hello @AmauryDef 
Your solution is good, but I think we need to solve it inside library.

**Comment by AmauryDef** [comment]
Of course it would be better. This can be put directly inside the library, by placing the last line into the closeLeft/closeRight function. And then adding an instruction on GitHub to tell people that they have to put the Observer inside their viewDidLoad() to make it work.

**Comment by RomanPodymov** [comment]
@AmauryDef So your solution can be used as a temporal, just to finish important project for example.

**Comment by AmauryDef** [comment]
Yes and it's will be useful for many people I think. But the developers of the library can use what I said and integrate it directly, I think it would be steady ;)
