### ISSUE TITLE
call menu from a page inside the project

### ISSUE THREAD

**Issue by moschino1** [dekatotoro/SlideMenuControllerSwift#34]
Hi,

i'm new in iOS and swift.
I'm trying to call your menu from a page that is not my initial page but is not linking my button to the SlideMenuController class.
I would like to call the createMenuFunction from a UIViewControl called programmatically and not from the AppDelegate.swift
Is it possible? How to do this?

Thanks a lot

**Comment by analuisamartins** [comment]
Hi,
I have the same need, it took me a while to figure out, but this is working: 
(I'm new to swift and ios to)

I have an IntroViewController.swift with a button and in the button's action:

    @IBAction func buttonPressed(sender: UIButton) {
    
        var storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("MainViewController") as! MainViewController
        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("LeftViewController") as! LeftViewController
        let rightViewController = storyboard.instantiateViewControllerWithIdentifier("RightViewController") as! RightViewController
        
        let nvc: UINavigationController = UINavigationController(rootViewController: mainViewController)
        
        leftViewController.mainViewController = nvc
        
        let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController, rightMenuViewController: rightViewController)
        
        // navigate to next view        
        self.presentViewController(slideMenuController, animated: false, completion: nil)
    }


And in MainViewController.swift I'm calling self.setNavigationBarItem() in viewDidLoad instead of viewWillAppear (still do not know why...):

    override func viewDidLoad() {
        super.viewDidLoad()
        self.setNavigationBarItem()
    }

Hope this helps ;)

**Comment by moschino1** [comment]
Yes, I solved it!
Thanks a lot!
