### ISSUE TITLE
Import from cocoapods

### ISSUE THREAD

**Issue by ivangodfather** [dekatotoro/SlideMenuControllerSwift#35]
When i get the SliderMenuControllerSwift from cocoapods, i can't use it since the imports doesnt work. Im am able to "Import SlideMenuControllerSwift" but i dont have any method SlideMenuController(mainViewController: mainViewC ... can you have a look at it?

**Comment by ivangodfather** [comment]
I have use_frameworks! in the Cocoa pod file

**Comment by dekatotoro** [comment]
Hi, Thank you Feedback.

Cocoapods was supported.
Please try again.

**Comment by ivangodfather** [comment]
now its working properly?

**Comment by dekatotoro** [comment]
yeah

**Comment by dekatotoro** [comment]
I'm sorry.
I will modify the access modifier for CocoaPods library.

**Comment by smahajan28** [comment]
Any Update?

**Comment by dekatotoro** [comment]
Cocoapods is already fully supported.
Close this issue.

**Comment by ivangodfather** [comment]
Since when?

On 12 November 2015 at 15:08, Yuji Hato <notifications@github.com> wrote:

> Cocoapods is already fully supported.
> Close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dekatotoro/SlideMenuControllerSwift/issues/35#issuecomment-156110886>
> .
>



-- 
Este mensaje se dirige a su destinatario y puede contener información
confidencial sometida a secreto profesional o cuya divulgación esté
prohibida por la Legislación Vigente. Cualquier persona distinta a su
destinataria tiene prohibida su reproducción, uso, divulgación o impresión
total o parcial. Si ha recibido este mensaje por error, notifíquelo de
inmediato al remitente borrando el mensaje original juntamente con sus
ficheros anexos. Gracias.

**Comment by dekatotoro** [comment]
This commit.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/3f1772c1a17969c3fffa22c0d66d3052bd9f739c
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/da1fb6973ddc2d82cd18a74c01e7c219a0026cdc
