### ISSUE TITLE
How to back previous viewcontroller?

### ISSUE THREAD

**Issue by haydarKarkin** [dekatotoro/SlideMenuControllerSwift#36]
Hi,

I can't pushviewcontroller, I use your method which is called changeviewcontroller, so I cant use poptorootviewcontroller. What should I do to reform for this situation.

Thanks,

Haydar

**Comment by dekatotoro** [comment]
Hi, 

I'm sorry, I do not know a little exact situation.
If there is a sample project, might I can be solved.

**Comment by haydarKarkin** [comment]
Hi again,

Firstly, from right slider, I call my view controller as following:

    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        let currentCell = self.tableView.cellForRowAtIndexPath(indexPath)
        println(indexPath.row)
     
        var tag = String(indexPath.row+1)
        
        let webViewController = storyboard!.instantiateViewControllerWithIdentifier("WebViewController") as! WebViewController
        webViewController.delegate = self
        self.webViewController = UINavigationController(rootViewController: webViewController)

        webViewController.tagTable = tag
        //self.presentViewController(webViewController, animated: false, completion: nil)
        self.slideMenuController()?.changeMainViewController(self.webViewController, close: true)
    }

After, in webViewController, I want to open (or back) mainViewController, however I can't do that. 
    @IBAction func didTouchToMain(sender: UIButton) {
        delegate?.changeViewController(LeftMenu.Main)
    }
What should I do for that? 

Regards,

Haydar

**Comment by dhruv270** [comment]
Hi Haydar,

Can you please suggest/guide me how did you solve this issue? I have the same issue as `_ = navigationController?.popViewController(animated: true)` is not working for me.
