### ISSUE TITLE
What do I do if I don't want this as the rootViewController? 

### ISSUE THREAD

**Issue by instaqwe** [dekatotoro/SlideMenuControllerSwift#37]
This is working perfectly with the SlideMenuController as the rootViewController, however, I have a login view before that and I can't seem to get it to work without setting it as the rootview. 
How would I go about doing this? 
Appriciate any help :)

**Comment by lrojas94** [comment]
May I ask how did you solve this?

**Comment by instaqwe** [comment]
I use this function as I'm logging in: 

      func createSlideViewAndScrollViewAndPresentThem(){
        var storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let mainViewController = storyboard.instantiateViewControllerWithIdentifier("SwipeViewController") as! UIViewController
        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("LeftViewController") as! LeftViewController
        
        leftViewController.mainViewController = mainViewController
        
        let slideMenuController = SlideMenuController(mainViewController:mainViewController, leftMenuViewController: leftViewController)
        
        self.presentViewController(slideMenuController, animated: true, completion: nil)
    }

**Comment by lrojas94** [comment]
Thanks a lot! that will certainly do
