### ISSUE TITLE
Implementing a tableview on the left viewcontroller

### ISSUE THREAD

**Issue by decao** [dekatotoro/SlideMenuControllerSwift#4]
Hi Dekatotoro, first of all, thank you very much for making this library, is really easy to use and by far the best slide out menu made with Swift, that i could find.

So here's the deal, i'm trying to implement a Table View on my sidebar ( left view ) so i can create a simple menu.

I'm adding the tableview via storyboard, the view is being added on the app via AppDelegate.swift just like in the example:

   private func createMenuView() {
          var storyboard = UIStoryboard(name: "Main", bundle: nil)
          let mainView = storyboard.instantiateViewControllerWithIdentifier("mainView") as ViewController
          mainView.addLeftBarButtonWithImage(UIImage(named: "menuicon")!)
          let sideView = storyboard.instantiateViewControllerWithIdentifier("sideView") as SidebarViewController // this is the sidebar
          
          let nvc: UINavigationController = UINavigationController(rootViewController: mainView)
          
          let slideOutMenu = SlideMenuController(mainViewController: nvc, leftMenuViewController: sideView)
          
          nvc.navigationBar.barTintColor = UIColor(red: 0.20392156862, green: 0.59607843137, blue: 0.85882352941, alpha: 1.0) //rgba(52, 152, 219,1.0)
          nvc.navigationBar.barStyle = UIBarStyle.Black
          nvc.navigationBar.tintColor = UIColor.whiteColor()
          nvc.navigationBar.translucent = false
          
          UIApplication.sharedApplication().statusBarStyle = UIStatusBarStyle.LightContent
     
          
          self.window?.backgroundColor = UIColor(red: 236.0, green: 238.0, blue: 241.0, alpha: 1.0)
          self.window?.rootViewController = slideOutMenu
          self.window?.makeKeyAndVisible()
          
     }

The problem is the tableview is being added above everything, any idea on why this is happening

![tableview](https://cloud.githubusercontent.com/assets/3464383/5743893/6a88b64e-9c03-11e4-86a5-4b3647151c58.gif)

Thank you!

**Comment by qrodgers13** [comment]
decao, did you solve this problem? I am having a very similar one that I have been unable to figure out. Thanks!

**Comment by decaobr** [comment]
Hey @qrodgers13 is actually pretty easy to solve, you can remove the MENU view controller from the Storyboard, and replace by a table view controller VIEW.

Or you can add constrains to your current table in your view.

**Comment by qrodgers13** [comment]
@decaobr Thank you! You were right - added some simple constraints and it worked right away.
