### ISSUE TITLE
error: Multiple commands produce

### ISSUE THREAD

**Issue by bhushanrocks412** [dekatotoro/SlideMenuControllerSwift#412]
error: Multiple commands produce '/Users/rahulparab/Library/Developer/Xcode/DerivedData/SlideMenuControllerSwift-dtzoqcqafwlgjteusljbkxndynde/Build/Products/Debug-iphoneos/SlideMenuControllerSwift.app/Info.plist':
1) Target 'SlideMenuControllerSwift' (project 'SlideMenuControllerSwift') has copy command from '/Users/rahulparab/Downloads/SlideMenuControllerSwift-master/Source/Info.plist' to '/Users/rahulparab/Library/Developer/Xcode/DerivedData/SlideMenuControllerSwift-dtzoqcqafwlgjteusljbkxndynde/Build/Products/Debug-iphoneos/SlideMenuControllerSwift.app/Info.plist'
2) Target 'SlideMenuControllerSwift' (project 'SlideMenuControllerSwift') has process command with output '/Users/rahulparab/Library/Developer/Xcode/DerivedData/SlideMenuControllerSwift-dtzoqcqafwlgjteusljbkxndynde/Build/Products/Debug-iphoneos/SlideMenuControllerSwift.app/Info.plist'

could you help me on this.

**Comment by PrashantKT** [comment]
To fix this issue

Goto build Phases -> Make sure you have correct target selected (see left side list) -> Remove info.pllist file from Copy bundle and resources folder -> Clean project and Compile

**Comment by bhushanrocks412** [comment]
thank you
