### ISSUE TITLE
[Typo] var leftTapGetsture: UITapGestureRecognizer?

### ISSUE THREAD

**Issue by JobsLong** [dekatotoro/SlideMenuControllerSwift#42]
Line:  55 -> `Source/SlideMenuController.swift`

```
var leftTap`Getsture`: UITapGestureRecognizer?
```

should:

```
var leftTap`Gesture`: UITapGestureRecognizer?
```

**Comment by dekatotoro** [comment]
Thanks you.
Fixed at
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/e9cd632827652496865b7c5f301b0908cc03fd44
