### ISSUE TITLE
IMPORTANT! ViewDidAppear of every view that i tapped on the menu call again when i dismiss modelly presented controller on slide menu

### ISSUE THREAD

**Issue by htarwara6245** [dekatotoro/SlideMenuControllerSwift#46]
I write everything like almost your project in my project.First of all i would like to tell my stage before the error

There are 4 controllers in my slide menu.So, there will be 3 menus and 1 button.
Please Check - > http://puu.sh/it83l/1af3a63f09.png

Because of i set "Auction Latest" in AppDelegate like yours,it will be display first in the MainViewController.

Then
->I slide out the menu and tapped "Auction Latest" again,that view display at Main View again,
->Then I slide out and tapped "Auction Past" again,that view display
->Then "Auction Recent",that display again(Note:These state are important)
Then I tapped "Sign In" button on my slide menu,It will present modally over slide menu
Please Check -> http://puu.sh/it7Z0/adaf9a4247.png

You will see cross "X" button on the SignInView.When i click,it dismiss and you will see the left menu again.

So the problem is,every time i dismiss the sign in view which presented modally,the menu(views) that i visited "viewDidAppear()" called again.I wonder why?

Here is my console log after i dismiss my modally presented sign in view

Auction : Latest viewDidAppear
Auction : Latest viewDidAppear
Auction : Past viewDidAppear
Auction : Recent ViewDidAppear

Please check your slide menu again Sir,thanks.
I have been using your slide menu for my project since the beginning.

**Comment by htarwara6245** [comment]
@dekatotoro,

Please Test This,I am saying the truth,there is nothing wrong with my project.

https://drive.google.com/file/d/0B1LMfbEl-KLhbnRxUThqWURsRFk/view?usp=sharing

http://puu.sh/iy1Kg/f94d97cbe3.png
This state was,
First,it loaded with Main View Controller.So,"Main View ViewDidAppear"
Second,I changed to Swift View,So,"Swift View ViewDidAppear"
Third,I changed to Java View,So,"Java View ViewDidAppear"

Then I clicked SignIn Button to appear modally presented View.Then i click dismiss.

Why "Main View ViewDidAppear","Swift View ViewDidAppear" and "Java View ViewDidAppear" call again?

If my project having network call in viewDidAppear of each view,it will three async call for three view.

So,Please Help!!
This is serious problem,i think

**Comment by dekatotoro** [comment]
It is a Cause that was not able to removeViewController at SlideMenuController#changeMainViewController.
Try it from the latest version has been fixed.
