### ISSUE TITLE
Previous View in Editing mode

### ISSUE THREAD

**Issue by ed-mejia** [dekatotoro/SlideMenuControllerSwift#47]
Hi, great controller I'm having this issue at the moment:

If the previous controller is in editing mode (Keyboard up) when you change to the new screen, the Keyboard remains on screen.

**Comment by pavm035** [comment]
Same issue here

**Comment by Codeido** [comment]
If i understood your question, you can use .resignFirstResponder() to close the keyboard while the menu is opening.
