### ISSUE TITLE
scrollsToTop does not work

### ISSUE THREAD

**Issue by AmeerTgh** [dekatotoro/SlideMenuControllerSwift#48]
when switch to view controller agin, tap on scroll (for scroll to top) in tableview does not work!

**Comment by s0meone** [comment]
#49 fixes this issue

**Comment by dekatotoro** [comment]
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/24e2e6b084c24938bb797726480cd04273b55327
fixed this issue

**Comment by xrelative** [comment]
Apparently it was not correct this issue, not work for me.

**Comment by trinhngocthuyen** [comment]
@xrelative: The same problem happened to me though this issue was already closed. I have figured out the reason: *maybe there is a scrollview inside the Left/Right menu*. Just disable scrollsToTop for that scrollview.

**Comment by xrelative** [comment]
@trinhngocthuyen: thanks! I had to disable the scroll left menu.
