### ISSUE TITLE
Disable menus eg. during login/logout screen

### ISSUE THREAD

**Issue by sunny596** [dekatotoro/SlideMenuControllerSwift#5]
Thanks for writing this great menu. I am just learning and this is so helpful. 
It is clear and very well written. 

Would there be a way to disable the both the menus ? Say, during a login/logout screen ?
And how would you suggest I switch to another viewController for this login/logout process. 

I am not an advanced user. Any help is appreciated.

Great job !

**Comment by moriyaman** [comment]
:+1:

**Comment by htarwara6245** [comment]
Why try using your login/logout screen as initial view controller.After pressing log in,navigate to main controller which uses slide out.You can also set the controller that will use slide out in AppDelegate.

**Comment by dekatotoro** [comment]
Hi, Thank you feedback.
Application of design I think there are various.
I've updated the Sample with additional menu hide sample.
I do not know what you want, but Please try to reference.

**Comment by htarwara6245** [comment]
Sir,Thank you for your updates.I saw a issue that i can still do the slide out when i rotated the NonMenuViewController from portrait to landscape and when i turn my device from landscape to portrait,slide appear again.

**Comment by dekatotoro** [comment]
Hi, Thank you feedback.
NonMenuViewController Rotate supported.

**Comment by sunny596** [comment]
Ah, thank you!
This is what I was looking for.

Thanks for the quick response. 
Cheers !
