### ISSUE TITLE
Expose mainViewController

### ISSUE THREAD

**Issue by ollieatkinson** [dekatotoro/SlideMenuControllerSwift#55]
Why is this property hidden? It might be sometimes useful to have a reference to this view controller when transitioning.

Here is my scenario

```
VC1 calls app://VC2
UIApplication calls router
router matches the path
match block grabs the context object on the mainViewController
match block sets the context object on VC2
match block calls slideMenuController to changeMainViewController to VC2
```

Unless there is a pressing reason for this being hidden can we remove its private modifier?

**Comment by dekatotoro** [comment]
It is now supported.
Please use version1.2.3.
