### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by renanoaraujo** [dekatotoro/SlideMenuControllerSwift#57]
Hello . Entering the view NonMenuController.swift , the left slider function does not work quite the way it promised. But by turning the iphone, it activates the slide function. In other words , I wondered how to disable anyway , regardless of the rotation , the slider function. I wonder how to solve it . Thank you.

**Comment by dekatotoro** [comment]
It is a bug. Now supported.
Please use version1.2.2.
