### ISSUE TITLE
I am stuck with your code when customizing it.

### ISSUE THREAD

**Issue by lostpupil** [dekatotoro/SlideMenuControllerSwift#6]
First of all, thanks for your repo here. I find out that your README said set up the code in app delegate, and commonly, people would see a sign in or sign up view first, after I successfully sign in, then I would get this view. So How do I wrote this with storyboard?
![image](https://cloud.githubusercontent.com/assets/2015695/5953549/5ae49734-a7c6-11e4-9949-a7d4d4f57046.png)

Well here I should set ground view controller as main view controller, and I find it needs a navigation controller, and I am stuck here.
So, how do I get this work?

**Comment by lostpupil** [comment]
And ViewController2 should be the left one, view controller 3 should be the right one.

**Comment by htarwara6245** [comment]
Sir,i don't quite understand what you want to do.Can you please describe step by step which you want to do.I am one of the user of his slide controller.So,I might solve your problem.

**Comment by lostpupil** [comment]
I solved it. Like below.
 if (user != nil) {
                println("sign in successfully")
                
                // login in and save last login time to cloud
                var login_time = NSDate().timeIntervalSince1970
                user["lastLoginAt"] = login_time
                user.saveInBackground()
                // init ground story board and ground view controller
                var storyboard = UIStoryboard(name: "Ground", bundle: nil)
                var destcontroller = storyboard.instantiateViewControllerWithIdentifier("ground") as UIViewController
                
                // init side bar storyboard and side bar view controller
                var sidebarstoryboard = UIStoryboard(name: "SideBar", bundle: nil)
                var leftViewController = sidebarstoryboard.instantiateViewControllerWithIdentifier("sidebar") as UIViewController
                // init navigation controller and slide menu controller
                let nvc: UINavigationController = UINavigationController(rootViewController: destcontroller)
                let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController)
                // use present way to display new page
                self.presentViewController(slideMenuController, animated: true, completion: nil)
            } else {
                //Something bad has ocurred
                var errorString:NSString = error.description as NSString
                var errorAlertView:UIAlertView = UIAlertView(title: "Error", message: errorString, delegate: nil, cancelButtonTitle: "OK")
                errorAlertView.show()
            }

**Comment by dekatotoro** [comment]
Hi,I'm sorry answer is slow.
It was nice and seemed to be solved.
We are doing things like sample project was also similar, please try to be helpful.
