### ISSUE TITLE
is it possible to disable the pan gesture action to bring the drawer? 

### ISSUE THREAD

**Issue by jasan-s** [dekatotoro/SlideMenuControllerSwift#62]
I want just the nav bar button to open but the pan gesture to close or tap back to other controller to close.

**Comment by ashishfission** [comment]
Same requirement

**Comment by gali8** [comment]
try self.options.panFromBezel = false

**Comment by giaotuancse** [comment]
same problem when trying to disable gesture. Anyone fix it?

**Comment by veegee** [comment]
@giaotuancse This doesn't work.

**Comment by haiqiang** [comment]
did anyone got this working? I'm trying to do the same thing.

**Comment by dhiaeldeen** [comment]
these work for me..

        self.slideMenuController()?.removeLeftGestures()
        self.slideMenuController()?.removeRightGestures()

**Comment by haiqiang** [comment]
Sorry, I commented on the wrong post. Didn't meant to comment on this problem.

**Comment by haiqiang** [comment]
using the following will disable the pan gesture to close the menu as well.
self.slideMenuController()?.removeLeftGestures()
self.slideMenuController()?.removeRightGestures()

is there anyway to do what jasan-s commented? 
"nav bar button to open but the pan gesture to close or tap back to other controller to close."

**Comment by Pluto-Y** [comment]
```
SlideMenuOptions.panFromBezel = false
SlideMenuOptions.rightPanFromBezel = false
```
This code can disable the pan for open the menu.
But it also can pan or tap gesture to close the menu.
Please try it.

**Comment by Pluto-Y** [comment]
@haiqiang Please try it again and tell me the result.

**Comment by haiqiang** [comment]
@Pluto-Y it's working. Thank you very much :)

**Comment by Pluto-Y** [comment]
You are welcome.
