### ISSUE TITLE
xcode7 swift2.0 slideMenuControllerSwift error

### ISSUE THREAD

**Issue by lenvonsam** [dekatotoro/SlideMenuControllerSwift#65]
i update xocde version to 7 , slideMenuController has many errors,could you helper me to fix these error in xcode7

**Comment by A1iAshoor** [comment]
+1

**Comment by MarioTi** [comment]
this work for mi in Xcode 7 and 7.1 

https://github.com/dekatotoro/SlideMenuControllerSwift/releases/tag/2.0.0

**Comment by A1iAshoor** [comment]
This fixed all swift 2.0 related errors:
pod 'SlideMenuControllerSwift', :head

**Comment by mudithsilva** [comment]
Thanks !! @MarioTi
