### ISSUE TITLE
Use in combination with tab bar controller

### ISSUE THREAD

**Issue by FejZa** [dekatotoro/SlideMenuControllerSwift#7]
Hi, can't find any other way to contact you, so I'm posting this as an issue, it actually is not, more a feature?

I'm fairly new to iOS Development and trying to user your SlideMenuControllerSwift on an application with tab bar controller. Everything works fine, except that the iOS default behaviour when doing segues is  not working. What I mean: I tap a button which triggers a segue to another view controller. No the navigation bar at the top should enable a "< back" button by default, which it doesn't. Only on my first tab bar item.

Can you tell me, whether this can be "fixed"?

Thank you.

**Comment by dekatotoro** [comment]
Hi. Thank you feedback.

Sorry, Can not be a little understanding what circumstances. I might understand it and me up the other little detailed videos or sample code.

**Comment by FejZa** [comment]
Hi, 

 

I will prepare a sample Xcode project for you. How can I send you the project?

 

Von: Yuji Hato [mailto:notifications@github.com] 
Gesendet: Friday, February 6, 2015 1:33 PM
An: dekatotoro/SlideMenuControllerSwift
Cc: Dino Fejzagic
Betreff: Re: [SlideMenuControllerSwift] Use in combination with tab bar controller (#7)

 

Hi. Thank you feedback.

Sorry, Can not be a little understanding what circumstances. I might understand it and me up the other little detailed videos or sample code.

**Comment by dekatotoro** [comment]
Hi, 

Please send it to this email.
hatoyujidev@gmail.com

**Comment by dekatotoro** [comment]
Hi,

Please raise a different issue Once any problems there.
I will close once.

**Comment by Sadmansamee** [comment]
Hey Fejza or dekatotoro can we see a sample of this kind of scenario?

**Comment by aakarshsasi** [comment]
I'm also having issue with tab view
