### ISSUE TITLE
Open menu item with a button

### ISSUE THREAD

**Issue by MarioTi** [dekatotoro/SlideMenuControllerSwift#72]
i can call it a menu item from a button?

Thxs

**Comment by karlingen** [comment]
Yes. Add a button and create a touch action and call this:
`self.slideMenuController()?.openLeft()`

**Comment by LouisMazel** [comment]
Hi, 

(I'm beginner in swift)
When you put a button with func "addLeftBarButtonWithImage", how you connect the button with an action (open menu).

Thanks :)

**Comment by Codeido** [comment]
@LouisMazel if you use addLeftBarButtonWithImage, the action toggleLeft() that open the left menu is already connected.

Thanks
