### ISSUE TITLE
Navigation Bar is not showing

### ISSUE THREAD

**Issue by daimagine** [dekatotoro/SlideMenuControllerSwift#9]
I really like your work and I appreciate it. But I found some difficulties while working with your SlideMenuController. I implement the same way as your example but my navigation bar is not showing. Could you help?

**Comment by mattblang** [comment]
@daimagine Did you figure this out?  I am having the same problem.

**Comment by daimagine** [comment]
@mattblang Unfortunately I had to use another slide menu due to design changes

**Comment by mattblang** [comment]
@daimagine Could I ask which one you went with?
